apiVersion: v1
kind: Secret
metadata:
  name: wordpress-db-secret
  namespace: wordpress-nfs
type: Opaque
stringData:
  mariadb-root-password: CHANGE_ME_ROOT_PASSWORD
  mariadb-database: wordpress
  mariadb-user: CHANGE_ME_DB_USER
  mariadb-password: CHANGE_ME_DB_PASSWORD
